import { LucideIcon, Languages, Plane, Hotel, Car, Ship, GraduationCap, FileCheck, Subtitles, Globe, Handshake } from 'lucide-react';

export type Language = 'en' | 'es' | 'pt' | 'zh' | 'he' | 'ar' | 'ru' | 'ro' | 'nl' | 'no' | 'hi' | 'ja' | 'fr' | 'it' | 'de' | 'ko' | 'fi' | 'el';

export interface Service {
  id: string;
  icon: LucideIcon;
  image: string;
  externalPlatformLink?: string;
  slides?: string[];
  videos?: string[];
  partners?: { name: string; image: string }[];
  translations: Record<Language, {
    title: string;
    description: string;
  }>;
}

export const WHATSAPP_NUMBER = "5511999999999";
export const WHATSAPP_BASE_URL = `https://wa.me/${WHATSAPP_NUMBER}`;
export const TRAVEL_PLATFORM_URL = "https://www.comprarviagem.com.br/vgoire'strips/home";
export const OFFICIAL_WEBSITE_URL = "https://tevgoire.com.br/";

export const LANGUAGES: { code: Language; name: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'en', name: 'English', dir: 'ltr' },
  { code: 'es', name: 'Español', dir: 'ltr' },
  { code: 'pt', name: 'Português (BR)', dir: 'ltr' },
  { code: 'zh', name: '中文', dir: 'ltr' },
  { code: 'he', name: 'עברית', dir: 'rtl' },
  { code: 'ar', name: 'العربية', dir: 'rtl' },
  { code: 'ru', name: 'Русский', dir: 'ltr' },
  { code: 'ro', name: 'Română', dir: 'ltr' },
  { code: 'nl', name: 'Nederlands', dir: 'ltr' },
  { code: 'no', name: 'Norsk', dir: 'ltr' },
  { code: 'hi', name: 'हिन्दी', dir: 'ltr' },
  { code: 'ja', name: '日本語', dir: 'ltr' },
  { code: 'fr', name: 'Français', dir: 'ltr' },
  { code: 'it', name: 'Italiano', dir: 'ltr' },
  { code: 'de', name: 'Deutsch', dir: 'ltr' },
  { code: 'ko', name: '한국어', dir: 'ltr' },
  { code: 'fi', name: 'Suomi', dir: 'ltr' },
  { code: 'el', name: 'Ελληνικά', dir: 'ltr' },
];

export const UI_STRINGS: Record<Language, any> = {
  en: {
    tagline: "Premium Global Solutions",
    visitWebsite: "Visit Official Website",
    requestQuote: "Request a Quote via WhatsApp",
    accessPlatform: "Access Travel Platform",
    accessPartnersPlatform: "ACCESS  OUR  PARTNERS  PLATFORM  FOR  REFERENCE",
    secureService: "Secure and Confidential Service",
    back: "Back",
    excellence: "Excellence in Every Service",
    rateUs: "Rate us on Google",
    reviews: "CLIENT REVIEWS",
    partners: "OUR PARTNERS",
    privacyPolicy: "Privacy Policy",
    privacyContent: "VGOIRE is committed to protecting your privacy. This application does not collect personal data directly. Any information shared via WhatsApp or external links is handled by those respective platforms according to their own privacy policies. We do not share your information with third parties."
  },
  es: {
    tagline: "Soluciones Globales Premium",
    visitWebsite: "Visitar Sitio Oficial",
    requestQuote: "Solicitar Presupuesto por WhatsApp",
    accessPlatform: "Acceder a la Plataforma de Viajes",
    accessPartnersPlatform: "ACCEDER A LA PLATAFORMA DE NUESTROS SOCIOS PARA REFERENCIA",
    secureService: "Servicio Seguro y Confidencial",
    back: "Volver",
    excellence: "Excelencia en cada servicio",
    rateUs: "Califícanos en Google",
    reviews: "OPINIONES DE CLIENTES",
    partners: "NUESTROS SOCIOS",
    privacyPolicy: "Política de Privacidad",
    privacyContent: "VGOIRE se compromete a proteger su privacidad. Esta aplicación no recopila datos personales directamente. Cualquier información compartida a través de WhatsApp o enlaces externos es manejada por esas plataformas respectivas de acuerdo con sus propias políticas de privacidad. No compartimos su información con terceros."
  },
  pt: {
    tagline: "Soluções Globais Premium",
    visitWebsite: "Visitar Site Oficial",
    requestQuote: "Solicitar Orçamento via WhatsApp",
    accessPlatform: "Acessar Plataforma de Viagens",
    accessPartnersPlatform: "ACESSAR A PLATAFORMA DE NOSSOS PARCEIROS PARA REFERÊNCIA",
    secureService: "Serviço Seguro e Confidencial",
    back: "Voltar",
    excellence: "Excelência em cada serviço",
    rateUs: "Avalie-nos no Google",
    reviews: "AVALIAÇÕES DE CLIENTES",
    partners: "NOSSOS PARCEIROS",
    privacyPolicy: "Política de Privacidade",
    privacyContent: "A VGOIRE está comprometida em proteger sua privacidade. Este aplicativo não coleta dados pessoais diretamente. Qualquer informação compartilhada via WhatsApp ou links externos é tratada por essas respectivas plataformas de acordo com suas próprias políticas de privacidade. Não compartilhamos suas informações com terceiros."
  },
  zh: {
    tagline: "优质全球解决方案",
    visitWebsite: "访问官方网站",
    requestQuote: "通过 WhatsApp 请求报价",
    accessPlatform: "访问旅游平台",
    accessPartnersPlatform: "访问我们的合作伙伴平台以供参考",
    secureService: "安全保密的服务",
    back: "返回",
    excellence: "卓越的服务",
    rateUs: "在 Google 上评价我们",
    reviews: "客户评价",
    partners: "我们的合作伙伴",
    privacyPolicy: "隐私政策",
    privacyContent: "VGOIRE 致力于保护您的隐私。本应用不直接收集个人数据。通过 WhatsApp 或外部链接共享的任何信息均由这些相应平台根据其自身的隐私政策处理。我们不会与第三方共享您的信息。"
  },
  he: {
    tagline: "פתרונות גלובליים פרימיום",
    visitWebsite: "בקר באתר הרשמי",
    requestQuote: "בקש הצעת מחיר בוואטסאפ",
    accessPlatform: "גישה לפלטפורמת נסיעות",
    accessPartnersPlatform: "גישה לפלטפורמת השותפים שלנו לעיון",
    secureService: "שירות מאובטח וחסוי",
    back: "חזור",
    excellence: "מצוינות בכל שירות",
    rateUs: "דרגו אותנו בגוגל",
    reviews: "ביקורות לקוחות",
    partners: "השותפים שלנו",
    privacyPolicy: "מדיניות פרטיות",
    privacyContent: "VGOIRE מחויבת להגן על הפרטיות שלך. אפליקציה זו אינה אוספת נתונים אישיים באופן ישיר. כל מידע המשותף באמצעות WhatsApp או קישורים חיצוניים מטופל על ידי הפלטפורמות המתאימות בהתאם למדיניות הפרטיות שלהן. איננו משתפים את המידע שלך עם צדדים שלישיים."
  },
  ar: {
    tagline: "حلول عالمية متميزة",
    visitWebsite: "زيارة الموقع الرسمي",
    requestQuote: "طلب عرض سعر عبر واتساب",
    accessPlatform: "الوصول إلى منصة السفر",
    accessPartnersPlatform: "الوصول إلى منصة شركائنا للمرجع",
    secureService: "خدمة آمنة וسرية",
    back: "رجوع",
    excellence: "التميز في كل خدمة",
    rateUs: "قيمنا على Google",
    reviews: "آراء العملاء",
    partners: "شركاؤنا",
    privacyPolicy: "سياسة الخصوصية",
    privacyContent: "تلتزم VGOIRE بحماية خصوصيتك. لا يجمع هذا التطبيق البيانات الشخصية مباشرة. يتم التعامل مع أي معلومات يتم مشاركتها عبر WhatsApp أو الروابط الخارجية من قبل تلك المنصات المعنية وفقًا لسياسات الخصوصية الخاصة بها. نحن لا نشارك معلوماتك مع أطراف ثالثة."
  },
  ru: {
    tagline: "Премиальные глобальные решения",
    visitWebsite: "Посетить официальный сайт",
    requestQuote: "Запросить расчет в WhatsApp",
    accessPlatform: "Доступ к платформе",
    accessPartnersPlatform: "ДОСТУП К ПЛАТФОРМЕ НАШИХ ПАРТНЕРОВ ДЛЯ СПРАВКИ",
    secureService: "Безопасный и конфиденциальный сервис",
    back: "Назад",
    excellence: "Превосходство в каждой услуге",
    rateUs: "Оцените нас в Google",
    reviews: "ОТЗЫВЫ КЛИЕНТОВ",
    partners: "НАШИ ПАРТНЕРЫ",
    privacyPolicy: "Политика конфиденциальности",
    privacyContent: "VGOIRE стремится защищать вашу конфиденциальность."
  },
  ro: {
    tagline: "Soluții globale premium",
    visitWebsite: "Vizitează site-ul oficial",
    requestQuote: "Solicită o ofertă prin WhatsApp",
    accessPlatform: "Accesează platforma",
    accessPartnersPlatform: "ACCESEAZĂ PLATFORMA PARTENERILOR NOȘTRI PENTRU REFERINȚĂ",
    secureService: "Serviciu sigur și confidențial",
    back: "Înapoi",
    excellence: "Excelență în fiecare serviciu",
    rateUs: "Evaluează-ne pe Google",
    reviews: "RECENZII CLIENȚI",
    partners: "PARTENERII NOȘTRI",
    privacyPolicy: "Politica de confidențialitate",
    privacyContent: "VGOIRE se angajează să vă protejeze confidențialitatea."
  },
  nl: {
    tagline: "Premium wereldwijde oplossingen",
    visitWebsite: "Bezoek officiële website",
    requestQuote: "Offerte aanvragen via WhatsApp",
    accessPlatform: "Toegang tot platform",
    accessPartnersPlatform: "TOEGANG TOT HET PLATFORM VAN ONZE PARTNERS TER REFERENTIE",
    secureService: "Veilige en vertrouwelijke service",
    back: "Terug",
    excellence: "Uitmuntendheid in elke service",
    rateUs: "Beoordeel ons op Google",
    reviews: "KLANTBEOORDELINGEN",
    partners: "ONZE PARTNERS",
    privacyPolicy: "Privacybeleid",
    privacyContent: "VGOIRE zet zich in voor het beschermen van uw privacy."
  },
  no: {
    tagline: "Premium globale løsninger",
    visitWebsite: "Besøk offisiell nettside",
    requestQuote: "Be om tilbud via WhatsApp",
    accessPlatform: "Tilgang til plattform",
    accessPartnersPlatform: "TILGANG TIL VÅRE PARTNERES PLATTFORM FOR REFERANSE",
    secureService: "Sikker og konfidensiell tjeneste",
    back: "Tilbake",
    excellence: "Excellence i hver tjeneste",
    rateUs: "Vurder oss på Google",
    reviews: "KUNDEANMELDELSER",
    partners: "VÅRE PARTNERE",
    privacyPolicy: "Personvernregler",
    privacyContent: "VGOIRE er forpliktet til å beskytte ditt personvern."
  },
  hi: {
    tagline: "प्रीमियम वैश्विक समाधान",
    visitWebsite: "आधिकारिक वेबसाइट पर जाएं",
    requestQuote: "WhatsApp के माध्यम से कोट का अनुरोध करें",
    accessPlatform: "प्लेटफॉर्म तक पहुंचें",
    accessPartnersPlatform: "संदर्भ के लिए हमारे भागीदारों के प्लेटफॉर्म तक पहुंचें",
    secureService: "सुरक्षित और गोपनीय सेवा",
    back: "पीछे",
    excellence: "हर सेवा में उत्कृष्टता",
    rateUs: "हमें Google पर रेट करें",
    reviews: "ग्राहक समीक्षा",
    partners: "हमारे भागीदार",
    privacyPolicy: "गोपनीयता नीति",
    privacyContent: "VGOIRE आपकी गोपनीयता की रक्षा के लिए प्रतिबद्ध है।"
  },
  ja: {
    tagline: "プレミアムなグローバルソリューション",
    visitWebsite: "公式サイトにアクセス",
    requestQuote: "WhatsAppで見積もりを依頼する",
    accessPlatform: "プラットフォームにアクセス",
    accessPartnersPlatform: "参照用にパートナーのプラットフォームにアクセス",
    secureService: "安全で機密性の高いサービス",
    back: "戻る",
    excellence: "すべてのサービスにおける卓越性",
    rateUs: "Googleで評価する",
    reviews: "お客様の声",
    partners: "パートナー",
    privacyPolicy: "プライバシーポリシー",
    privacyContent: "VGOIREはお客様のプライバシー保護に努めています。"
  },
  fr: {
    tagline: "Solutions globales premium",
    visitWebsite: "Visiter le site officiel",
    requestQuote: "Demander un devis via WhatsApp",
    accessPlatform: "Accéder à la plateforme",
    accessPartnersPlatform: "ACCÉDER À LA PLATEFORME DE NOS PARTENAIRES POUR RÉFÉRENCE",
    secureService: "Service sécurisé et confidentiel",
    back: "Retour",
    excellence: "Excellence dans chaque service",
    rateUs: "Évaluez-nous sur Google",
    reviews: "AVIS CLIENTS",
    partners: "NOS PARTENAIRES",
    privacyPolicy: "Politique de confidentialité",
    privacyContent: "VGOIRE s'engage à protéger votre vie privée."
  },
  it: {
    tagline: "Soluzioni globali premium",
    visitWebsite: "Visita il sito ufficiale",
    requestQuote: "Richiedi un preventivo via WhatsApp",
    accessPlatform: "Accedi alla piattaforma",
    accessPartnersPlatform: "ACCEDI ALLA PIATTAFORMA DEI NOSTRI PARTNER PER RIFERIMENTO",
    secureService: "Servizio sicuro e riservato",
    back: "Indietro",
    excellence: "Eccellenza in ogni servizio",
    rateUs: "Valutaci su Google",
    reviews: "RECENSIONI CLIENTI",
    partners: "I NOSTRI PARTNER",
    privacyPolicy: "Informativa sulla privacy",
    privacyContent: "VGOIRE si impegna a proteggere la tua privacy."
  },
  de: {
    tagline: "Premium-Lösungen weltweit",
    visitWebsite: "Offizielle Website besuchen",
    requestQuote: "Angebot per WhatsApp anfordern",
    accessPlatform: "Plattform aufrufen",
    accessPartnersPlatform: "ZUGRIFF AUF DIE PLATTFORM UNSERER PARTNER ZUR REFERENZ",
    secureService: "Sicherer und vertraulicher Service",
    back: "Zurück",
    excellence: "Exzellenz in jedem Service",
    rateUs: "Bewerten Sie uns auf Google",
    reviews: "KUNDENBEWERTUNGEN",
    partners: "UNSERE PARTNER",
    privacyPolicy: "Datenschutzerklärung",
    privacyContent: "VGOIRE setzt sich für den Schutz Ihrer Privatsphäre ein."
  },
  ko: {
    tagline: "프리미엄 글로벌 솔루션",
    visitWebsite: "공식 웹사이트 방문",
    requestQuote: "WhatsApp으로 견적 요청",
    accessPlatform: "플랫폼 접속",
    accessPartnersPlatform: "참고용 파트너 플랫폼 접속",
    secureService: "안전하고 기밀이 유지되는 서비스",
    back: "뒤로",
    excellence: "모든 서비스에서의 탁월함",
    rateUs: "Google에서 평가하기",
    reviews: "고객 리뷰",
    partners: "파트너",
    privacyPolicy: "개인정보 처리방침",
    privacyContent: "VGOIRE는 귀하의 개인정보를 보호하기 위해 최선을 다하고 있습니다."
  },
  fi: {
    tagline: "Premium-tason globaalit ratkaisut",
    visitWebsite: "Vieraile virallisella verkkosivustolla",
    requestQuote: "Pyydä tarjous WhatsAppilla",
    accessPlatform: "Pääsy alustalle",
    accessPartnersPlatform: "PÄÄSY KUMPPANEIDEMME ALUSTALLE VIITTEEKSI",
    secureService: "Turvallinen ja luottamuksellinen palvelu",
    back: "Takaisin",
    excellence: "Erinomaisuus jokaisessa palvelussa",
    rateUs: "Arvioi meidät Googlessa",
    reviews: "ASIAKASARVOSTELUT",
    partners: "KUMPPANIMME",
    privacyPolicy: "Tietosuojakäytäntö",
    privacyContent: "VGOIRE on sitoutunut suojaamaan yksityisyyttäsi."
  },
  el: {
    tagline: "Premium παγκόσμιες λύσεις",
    visitWebsite: "Επισκεφθείτε την επίσημη ιστοσελίδα",
    requestQuote: "Ζητήστε προσφορά μέσω WhatsApp",
    accessPlatform: "Πρόσβαση στην πλατφόρμα",
    accessPartnersPlatform: "ΠΡΟΣΒΑΣΗ ΣΤΗΝ ΠΛΑΤΦΟΡΜΑ ΤΩΝ ΣΥΝΕΡΓΑΤΩΝ ΜΑΣ ΓΙΑ ΑΝΑΦΟΡΑ",
    secureService: "Ασφαλής και εμπιστευτική υπηρεσία",
    back: "Πίσω",
    excellence: "Αριστεία σε κάθε υπηρεσία",
    rateUs: "Αξιολογήστε μας στο Google",
    reviews: "ΚΡΙΤΙΚΕΣ ΠΕΛΑΤΩΝ",
    partners: "ΟΙ ΣΥΝΕΡΓΑΤΕΣ ΜΑΣ",
    privacyPolicy: "Πολιτική απορρήτου",
    privacyContent: "Η VGOIRE δεσμεύεται να προστατεύει το απόρρητό σας."
  }
};

export const SERVICES: Service[] = [
  {
    id: 'translations',
    icon: Languages,
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=800',
    translations: {
      en: { title: 'TRANSLATIONS', description: 'Certified translation services in 15+ languages including English, Spanish, Portuguese, French, and more. Highly qualified translators recognized in Brazil.' },
      es: { title: 'TRADUCCIONES', description: 'Servicios de traducción certificada en más de 15 idiomas. Traductores altamente calificados y reconocidos en Brasil.' },
      pt: { title: 'TRADUÇÕES', description: 'Serviços de tradução juramentada em mais de 15 idiomas. Tradutores altamente qualificados e reconhecidos no Brasil.' },
      zh: { title: '翻译', description: '提供15种以上语言的认证翻译服务。巴西认可的高素质翻译人员。' },
      he: { title: 'תרגומים', description: 'שירותי תרגום מאושרים ב-15+ שפות. מתרגמים מוסמכים ומוכרים בברזיל.' },
      ar: { title: 'الترجمة', description: 'خدمات ترجمة معتمدة بأكثر من 15 لغة. مترجمون مؤهلون تأهيلاً عالياً ومعترف بهم في البرازيل.' },
      ru: { title: 'ПЕРЕВОДЫ', description: 'Сертифицированные услуги перевода на 15+ языков. Высококвалифицированные переводчики, признанные в Бразилии.' },
      ro: { title: 'TRADUCERI', description: 'Servicii de traduceri autorizate în peste 15 limbi. Traducători înalt calificați și recunoscuți în Brazilia.' },
      nl: { title: 'VERTALINGEN', description: 'Beëdigde vertaaldiensten in 15+ talen. Hooggekwalificeerde vertalers erkend in Brazilië.' },
      no: { title: 'OVERSETTELSER', description: 'Sertifiserte oversettelsestjenester på 15+ språk. Høyt kvalifiserte oversettere anerkjent i Brasil.' },
      hi: { title: 'अनुवाद', description: '15+ भाषाओं में प्रमाणित अनुवाद सेवाएं। ब्राजील में मान्यता प्राप्त उच्च योग्य अनुवादक।' },
      ja: { title: '翻訳', description: '15言語以上の公認翻訳サービス。ブラジルで認められた高度な資格を持つ翻訳者。' },
      fr: { title: 'TRADUCTIONS', description: 'Services de traduction certifiée dans plus de 15 langues. Traducteurs hautement qualifiés reconnus au Brésil.' },
      it: { title: 'TRADUZIONI', description: 'Servizi di traduzione certificata in oltre 15 lingue. Traduttori altamente qualificati riconosciuti in Brasile.' },
      de: { title: 'ÜBERSETZUNGEN', description: 'Beglaubigte Übersetzungsdienste in über 15 Sprachen. Hochqualifizierte Übersetzer, die in Brasilien anerkannt sind.' },
      ko: { title: '번역', description: '15개 이상의 언어로 제공되는 공인 번역 서비스. 브라질에서 인정받는 고도로 숙련된 번역가.' },
      fi: { title: 'KÄÄNNÖKSET', description: 'Auktorisoidut käännöspalvelut yli 15 kielellä. Brasiliassa tunnustetut pätevät kääntäjät.' },
      el: { title: 'ΜΕΤΑΦΡΑΣΕΙΣ', description: 'Πιστοποιημένες μεταφραστικές υπηρεσίες σε 15+ γλώσσες. Υψηλά καταρτισμένοι μεταφραστές αναγνωρισμένοι στη Βραζιλία.' }
    }
  },
  {
    id: 'travel',
    icon: Plane,
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&q=80&w=800',
    externalPlatformLink: TRAVEL_PLATFORM_URL,
    translations: {
      en: { title: 'TRAVEL', description: 'Domestic and international flights worldwide. Explore the world with comfort and safety.' },
      es: { title: 'VIAJES', description: 'Vuelos nacionales e internacionales en todo el mundo. Explore el mundo con comodidad y seguridad.' },
      pt: { title: 'VIAGENS', description: 'Passagens aéreas domésticas e internacionais em todo o mundo. Explore o mundo com conforto e segurança.' },
      zh: { title: '旅游', description: '全球国内和国际航班。舒适安全地探索世界。' },
      he: { title: 'נסיעות', description: 'טיסות פנים ובינלאומיות ברחבי העולם. חקור את העולם בנוחות ובבטיחות.' },
      ar: { title: 'السفر', description: 'رحلات طيران محلية ودولية في جميع أنحاء العالم. استكشف العالم براحة وأمان.' },
      ru: { title: 'ПУТЕШЕСТВИЯ', description: 'Внутренние и международные рейсы по всему миру. Исследуйте мир с комфортом и безопасностью.' },
      ro: { title: 'CĂLĂTORII', description: 'Zboruri interne și internaționale în întreaga lume. Explorează lumea cu confort și siguranță.' },
      nl: { title: 'REIZEN', description: 'Binnenlandse en internationale vluchten wereldwijd. Verken de wereld met comfort en veiligheid.' },
      no: { title: 'REISER', description: 'Innlands- og utenlandsflyvninger over hele verden. Utforsk verden med komfort og sikkerhet.' },
      hi: { title: 'यात्रा', description: 'दुनिया भर में घरेलू और अंतर्राष्ट्रीय उड़ानें। आराम और सुरक्षा के साथ दुनिया का अन्वेषण करें।' },
      ja: { title: '旅行', description: '世界中の国内線および国際線。快適さと安全性を備えた世界を探索してください。' },
      fr: { title: 'VOYAGES', description: 'Vols nationaux et internationaux dans le monde entier. Explorez le monde avec confort et sécurité.' },
      it: { title: 'VIAGGI', description: 'Voli nazionali e internazionali in tutto il mondo. Esplora il mondo con comfort e sicurezza.' },
      de: { title: 'REISEN', description: 'Inlands- und internationale Flüge weltweit. Erkunden Sie die Welt mit Komfort und Sicherheit.' },
      ko: { title: '여행', description: '전 세계 국내 및 국제선 항공편. 편안하고 안전하게 세계를 탐험하세요.' },
      fi: { title: 'MATKUSTUS', description: 'Koti- ja ulkomaanlennot maailmanlaajuisesti. Tutki maailmaa mukavasti ja turvallisesti.' },
      el: { title: 'ΤΑΞΙΔΙΑ', description: 'Εσωτερικές και διεθνείς πτήσεις παγκοσμίως. Εξερευνήστε τον κόσμο με άνεση και ασφάλεια.' }
    }
  },
  {
    id: 'hotel-bookings',
    icon: Hotel,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800',
    externalPlatformLink: TRAVEL_PLATFORM_URL,
    translations: {
      en: { title: 'HOTEL BOOKINGS', description: 'Find the best hotels for your stay with exclusive rates worldwide.' },
      es: { title: 'RESERVAS DE HOTEL', description: 'Encuentre los mejores hoteles para su estancia con tarifas exclusivas en todo el mundo.' },
      pt: { title: 'RESERVAS DE HOTEL', description: 'Encontre os melhores hotéis para sua estadia com tarifas exclusivas em todo el mundo.' },
      zh: { title: '酒店预订', description: '在全球范围内以专属价格为您寻找最佳酒店。' },
      he: { title: 'הזמנת מלונות', description: 'מצא את המלונות הטובים ביותר לשהותך בתעריפים בלעדיים ברחבי העולם.' },
      ar: { title: 'حجز الفنادق', description: 'ابحث عن أفضل الفنادق لإقامتك بأسعار حصرية في جميع أنحاء العالم.' },
      ru: { title: 'БРОНИРОВАНИЕ ОТЕЛЕЙ', description: 'Найдите лучшие отели для вашего пребывания по эксклюзивным тарифам по всему миру.' },
      ro: { title: 'REZERVĂRI HOTELIERE', description: 'Găsiți cele mai bune hoteluri pentru sejurul dumneavoastră cu tarife exclusive în întreaga lume.' },
      nl: { title: 'HOTELBOEKINGEN', description: 'Vind de beste hotels voor uw verblijf met exclusieve tarieven wereldwijd.' },
      no: { title: 'HOTELLBOOKING', description: 'Finn de beste hotellene for ditt opphold med eksklusive priser over hele verden.' },
      hi: { title: 'होटल बुकिंग', description: 'दुनिया भर में विशेष दरों के साथ अपने प्रवास के लिए सर्वोत्तम होटल खोजें।' },
      ja: { title: 'ホテル予約', description: '世界中の限定料金で、滞在に最適なホテルを見つけてください।' },
      fr: { title: 'RÉSERVATIONS D\'HÔTEL', description: 'Trouvez les meilleurs hôtels pour votre séjour avec des tarifs exclusifs dans le monde entier.' },
      it: { title: 'PRENOTAZIONI HOTEL', description: 'Trova i migliori hotel per il tuo soggiorno con tariffe esclusive in tutto il mondo.' },
      de: { title: 'HOTELBUCHUNGEN', description: 'Finden Sie die besten Hotels für Ihren Aufenthalt mit exklusiven Preisen weltweit.' },
      ko: { title: '호텔 예약', description: '전 세계 독점 요금으로 숙박에 가장 적합한 호텔을 찾으세요.' },
      fi: { title: 'HOTELLIVARAUKSET', description: 'Löydä parhaat hotellit majoitukseesi eksklusiivisilla hinnoilla maailmanlaajuisesti.' },
      el: { title: 'ΚΡΑΤΗΣΕΙΣ ΞΕΝΟΔΟΧΕΙΩΝ', description: 'Βρείτε τα καλύτερα ξενοδοχεία για τη διαμονή σας με αποκλειστικές τιμές παγκοσμίως.' }
    }
  },
  {
    id: 'car-rental',
    icon: Car,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    externalPlatformLink: TRAVEL_PLATFORM_URL,
    translations: {
      en: { title: 'CAR RENTAL', description: 'Rent luxury, safe, and comfortable cars for your trips worldwide.' },
      es: { title: 'ALQUILER DE AUTOS', description: 'Alquile autos de lujo, seguros y cómodos para sus viajes en todo el mundo.' },
      pt: { title: 'ALUGUEL DE CARROS', description: 'Alugue carros luxuosos, seguros e confortáveis para suas viagens em todo o mundo.' },
      zh: { title: '租车服务', description: '为您的全球旅行租赁豪华、安全且舒适的汽车。' },
      he: { title: 'השכרת רכב', description: 'שכור רכבי יוקרה, בטוחים ונוחים לנסיעותיך ברחבי העולם.' },
      ar: { title: 'تأجير السيارات', description: 'استأجر سيارات فاخرة وآمنة ومريحة لرحلاتك حول العالم.' },
      ru: { title: 'ПРОКАТ АВТОМОБИЛЕЙ', description: 'Арендуйте роскошные, безопасные и комфортабельные автомобили для поездок по всему миру.' },
      ro: { title: 'ÎNCHIRIERI AUTO', description: 'Închiriați mașini de lux, sigure și confortabile pentru călătoriile dumneavoastră în întreaga lume.' },
      nl: { title: 'AUTOVERHUUR', description: 'Huur luxe, veilige en comfortabele auto\'s voor uw reizen wereldwijd.' },
      no: { title: 'BILUTLEIE', description: 'Lei luksuriøse, trygge og komfortable biler for dine reiser over hele verden.' },
      hi: { title: 'कार किराए पर लेना', description: 'दुनिया भर में अपनी यात्राओं के लिए लक्जरी, सुरक्षित और आरामदायक कारें किराए पर लें।' },
      ja: { title: 'レンタカー', description: '世界中の旅行のために、豪華で安全、かつ快適な車をレンタルしてください。' },
      fr: { title: 'LOCATION DE VOITURE', description: 'Louez des voitures de luxe, sûres et confortables pour vos voyages dans le monde entier.' },
      it: { title: 'NOLEGGIO AUTO', description: 'Noleggia auto di lusso, sicure e confortevoli per i tuoi viaggi in tutto il mondo.' },
      de: { title: 'AUTOVERMIETUNG', description: 'Mieten Sie luxuriöse, sichere und komfortable Autos für Ihre Reisen weltweit.' },
      ko: { title: '렌터카', description: '전 세계 여행을 위해 럭셔리하고 안전하며 편안한 자동차를 렌트하세요.' },
      fi: { title: 'AUTONVUOKRAUS', description: 'Vuokraa ylellisiä, turvallisia ja mukavia autoja matkoillesi maailmanlaajuisesti.' },
      el: { title: 'ΕΝΟΙΚΙΑΣΗ ΑΥΤΟΚΙΝΗΤΟΥ', description: 'Ενοικιάστε πολυτελή, ασφαλή και άνετα αυτοκίνητα για τα ταξίδια σας σε όλο τον κόσμο.' }
    }
  },
  {
    id: 'cruises',
    icon: Ship,
    image: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=800',
    slides: [
      'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1500021804447-2ca2eaaaabeb?auto=format&fit=crop&q=80&w=1200'
    ],
    translations: {
      en: { title: 'CRUISES', description: 'Luxury cruises with a variety of activities for families to explore beautiful destinations (Partner: Qualitours).' },
      es: { title: 'CRUCEROS', description: 'Cruceros de lujo con una variedad de actividades para familias para explorar destinos hermosos (Socio: Qualitours).' },
      pt: { title: 'CRUZEIROS', description: 'Cruzeiros luxuosos com uma variedade de atividades para as famílias explorarem destinos bonitos (Parceiro: Qualitours).' },
      zh: { title: '游轮', description: '豪华游轮，为家庭提供各种活动，探索美丽的目的地（合作伙伴：Qualitours）。' },
      he: { title: 'הפלגות', description: 'הפלגות יוקרה עם מגוון פעילויות למשפחות לחקור יעדים יפים (שותף: Qualitours).' },
      ar: { title: 'الرحلات البحرية', description: 'رحلات بحرية فاخرة مع مجموعة متنوعة من الأنشطة للعائلات لاستكشاف وجهات جميلة (الشريك: Qualitours).' },
      ru: { title: 'КРУИЗЫ', description: 'Роскошные круизы с разнообразными мероприятиями для семейного отдыха (Партнер: Qualitours).' },
      ro: { title: 'CROAZIERE', description: 'Croaziere de lux cu o varietate de activități pentru familii pentru a explora destinații frumoase (Partener: Qualitours).' },
      nl: { title: 'CRUISES', description: 'Luxe cruises met een verscheidenheid aan activiteiten voor gezinnen om prachtige bestemmingen te verkennen (Partner: Qualitours).' },
      no: { title: 'CRUISES', description: 'Luksuriøse cruise med en rekke aktiviteter for familier for å utforske vakre destinasjoner (Partner: Qualitours).' },
      hi: { title: 'क्रूज', description: 'सुंदर गंतव्यों का पता लगाने के लिए परिवारों के लिए विभिन्न गतिविधियों के साथ लक्जरी क्रूज (साझेदार: Qualitours)।' },
      ja: { title: 'クルーズ', description: '美しい目的地を探索するための家族向けのさまざまなアクティビティを備えた豪華クルーズ（パートナー：Qualitours）。' },
      fr: { title: 'CROISIÈRES', description: 'Croisières de luxe avec une variété d\'activités pour les familles pour explorer de belles destinations (Partenaire : Qualitours).' },
      it: { title: 'CROCIERE', description: 'Crociere di lusso con una varietà di attività per le famiglie per esplorare bellissime destinazioni (Partner: Qualitours).' },
      de: { title: 'KREUZFAHRTEN', description: 'Luxuskreuzfahrten mit einer Vielzahl von Aktivitäten für Familien, um wunderschöne Reiseziele zu erkunden (Partner: Qualitours).' },
      ko: { title: '크루즈', description: '가족이 아름다운 목적지를 탐험할 수 있는 다양한 활동을 갖춘 럭셔리 크루즈(파트너: Qualitours).' },
      fi: { title: 'RISTEILYT', description: 'Ylelliset risteilyt monipuolisilla aktiviteeteilla perheille kauniisiin kohteisiin tutustumiseen (Kumppani: Qualitours).' },
      el: { title: 'ΚΡΟΥΑΖΙΕΡΕΣ', description: 'Πολυτελείς κρουαζιέρες με ποικιλία δραστηριοτήτων για οικογένειες για να εξερευνήσουν όμορφους προορισμούς (Συνεργάτης: Qualitours).' }
    }
  },
  {
    id: 'language-classes',
    icon: GraduationCap,
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=800',
    translations: {
      en: { title: 'LANGUAGE CLASSES', description: 'Online English and Spanish classes for all levels. Learn at your own pace.' },
      es: { title: 'CLASES DE IDIOMAS', description: 'Clases de inglés y español en línea para todos los niveles. Aprenda a su propio ritmo.' },
      pt: { title: 'AULAS DE IDIOMAS', description: 'Aulas de inglês e espanhol online para todos os níveis. Aprenda no seu próprio ritmo.' },
      zh: { title: '语言课程', description: '适合所有级别的在线英语和西班牙语课程。按您自己的节奏学习。' },
      he: { title: 'שיעורי שפה', description: 'שיעורי אנגלית וספרדית אונליין לכל הרמות. למד בקצב שלך.' },
      ar: { title: 'دروس اللغة', description: 'دروس اللغة الإنجليزية والإسبانية عبر الإنترنت لجميع المستويات. تعلم بالسرعة التي تناسبك.' },
      ru: { title: 'ЯЗЫКОВЫЕ КУРСЫ', description: 'Онлайн-уроки английского и испанского языков для всех уровней.' },
      ro: { title: 'CURSURI DE LIMBI STRĂINE', description: 'Cursuri online de engleză și spaniolă pentru toate nivelurile.' },
      nl: { title: 'TAALLESSEN', description: 'Online lessen Engels en Spaans voor alle niveaus.' },
      no: { title: 'SPRÅKKURS', description: 'Online engelsk- og spanskkurs for alle nivåer.' },
      hi: { title: 'भाषा कक्षाएं', description: 'सभी स्तरों के लिए ऑनलाइन अंग्रेजी और स्पेनिश कक्षाएं।' },
      ja: { title: '語学クラス', description: 'すべてのレベルを対象としたオンラインの英語とスペイン語のクラス。' },
      fr: { title: 'COURS DE LANGUES', description: 'Cours d\'anglais et d\'espagnol en ligne pour tous les niveaux.' },
      it: { title: 'CLASSI DI LINGUA', description: 'Lezioni di inglese e spagnolo online per tutti i livelli.' },
      de: { title: 'SPRACHKURSE', description: 'Online-Englisch- und Spanischkurse für alle Niveaus.' },
      ko: { title: '언어 수업', description: '모든 수준을 위한 온라인 영어 및 스페인어 수업.' },
      fi: { title: 'KIELIKURSSIT', description: 'Online-englannin ja espanjan tunnit kaikille tasoille.' },
      el: { title: 'ΜΑΘΗΜΑΤΑ ΓΛΩΣΣΩΝ', description: 'Διαδικτυακά μαθήματα Αγγλικών και Ισπανικών για όλα τα επίπεδα.' }
    }
  },
  {
    id: 'training',
    icon: FileCheck,
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800',
    translations: {
      en: { title: 'EXAM TRAINING', description: 'Preparation for DELE, IELTS, TOEFL, and Duolingo exams. Achieve your goals.' },
      es: { title: 'ENTRENAMIENTO PARA EXÁMENES', description: 'Preparación para los exámenes DELE, IELTS, TOEFL y Duolingo. Alcance sus metas.' },
      pt: { title: 'TREINAMENTO PARA EXAMES', description: 'Preparação para os exames DELE, IELTS, TOEFL e Duolingo. Alcance seus objetivos.' },
      zh: { title: '考试培训', description: 'DELE、IELTS、TOEFL 和 Duolingo 考试准备。实现您的目标。' },
      he: { title: 'הכנה למבחנים', description: 'הכנה למבחני DELE, IELTS, TOEFL ו-Duolingo. השג את המטרות שלך.' },
      ar: { title: 'التدريب على الامتحانات', description: 'التحضير لامتحانات DELE و IELTS و TOEFL و Duolingo. حقق أهدافك.' },
      ru: { title: 'ПОДГОТОВКА К ЭКЗАМЕНАМ', description: 'Подготовка к экзаменам DELE, IELTS, TOEFL и Duolingo.' },
      ro: { title: 'PREGĂTIRE PENTRU EXAMENE', description: 'Pregătire pentru examenele DELE, IELTS, TOEFL și Duolingo.' },
      nl: { title: 'EXAMENTRAINING', description: 'Voorbereiding op DELE, IELTS, TOEFL en Duolingo examens.' },
      no: { title: 'EKSAMENSTRENING', description: 'Forberedelse til DELE, IELTS, TOEFL og Duolingo eksamener.' },
      hi: { title: 'परीक्षा प्रशिक्षण', description: 'DELE, IELTS, TOEFL और Duolingo परीक्षाओं की तैयारी।' },
      ja: { title: '試験対策', description: 'DELE、IELTS、TOEFL、Duolingo試験の準備。' },
      fr: { title: 'PRÉPARATION AUX EXAMENS', description: 'Préparation aux examens DELE, IELTS, TOEFL et Duolingo.' },
      it: { title: 'FORMAZIONE PER ESAMI', description: 'Preparazione per gli esami DELE, IELTS, TOEFL e Duolingo.' },
      de: { title: 'PRÜFUNGSVORBEREITUNG', description: 'Vorbereitung auf DELE-, IELTS-, TOEFL- und Duolingo-Prüfungen.' },
      ko: { title: '시험 교육', description: 'DELE, IELTS, TOEFL 및 Duolingo 시험 준비.' },
      fi: { title: 'VALMENTAUTUMINEN TENTTEIHIN', description: 'Valmistautuminen DELE-, IELTS-, TOEFL- ja Duolingo-kokeisiin.' },
      el: { title: 'ΠΡΟΕΤΟΙΜΑΣΙΑ ΕΞΕΤΑΣΕΩΝ', description: 'Προετοιμασία για εξετάσεις DELE, IELTS, TOEFL και Δουολινγο.' }
    }
  },
  {
    id: 'subtitling',
    icon: Subtitles,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=800',
    translations: {
      en: { title: 'SUBTITLING', description: 'Professional subtitling services in English, Spanish, and Portuguese.' },
      es: { title: 'SUBTITULADO', description: 'Servicios de subtitulado profesional en inglés, español y portugués.' },
      pt: { title: 'LEGENDAGEM', description: 'Serviços de legendagem profesional en inglés, español y portugués.' },
      zh: { title: '字幕服务', description: '英语、西班牙语和葡萄牙语的专业字幕服务。' },
      he: { title: 'כתוביות', description: 'שירותי כתוביות מקצועיים באנגלית, ספרדית ופורטוגזית.' },
      ar: { title: 'الترجمة المرئية', description: 'خدمات الترجمة المرئية الاحترافية باللغات الإنجليزية والإسبانية والبرتغالية.' },
      ru: { title: 'СУБТИТРЫ', description: 'Профессиональные услуги субтитрования на английском, испанском и португальском языках.' },
      ro: { title: 'SUBTITRARE', description: 'Servicii profesionale de subtitrare în engleză, spaniolă și portugheză.' },
      nl: { title: 'ONDERTITELING', description: 'Professionele ondertiteling in het Engels, Spaans en Portugees.' },
      no: { title: 'SUBTITLING', description: 'Profesjonelle tekstingstjenester på engelsk, spansk og portugisisk.' },
      hi: { title: 'सबटाइटलिंग', description: 'अंग्रेजी, स्पेनिश और पुर्तगाली में पेशेवर सबटाइटलिंग सेवाएं।' },
      ja: { title: '字幕', description: '英語、スペイン語、ポルトガル語のプロフェッショナルな字幕サービス。' },
      fr: { title: 'SOUS-TITRAGE', description: 'Services de sous-titrage professionnels en anglais, espagnol et portugais.' },
      it: { title: 'SOTTOTITOLAZIONE', description: 'Servizi di sottotitolazione professionale in inglese, spagnolo e portoghese.' },
      de: { title: 'UNTERTITELUNG', description: 'Professionelle Untertitelungsdienste in Englisch, Spanisch und Portugiesisch.' },
      ko: { title: '자막', description: '영어, 스페인어 및 포르투갈어 전문 자막 서비스.' },
      fi: { title: 'TEKSTITYS', description: 'Ammattimaiset tekstityspalvelut englanniksi, espanjaksi ja portugaliksi.' },
      el: { title: 'ΥΠΟΤΙΤΛΙΣΜΟΣ', description: 'Επαγγελματικές υπηρεσίες υποτιτλισμού στα Αγγλικά, Ισπανικά και Πορτογαλικά.' }
    }
  },
  {
    id: 'reviews',
    icon: Globe,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
    externalPlatformLink: 'https://g.page/r/CS9Ud_S-46syEAE/review',
    translations: {
      en: { title: 'CLIENT REVIEWS', description: 'See what our clients say about us and rate our services on Google.' },
      es: { title: 'OPINIONES DE CLIENTES', description: 'Vea lo que nuestros clientes dicen de nosotros y califique nuestros servicios en Google.' },
      pt: { title: 'AVALIAÇÕES DE CLIENTES', description: 'Veja o que nossos clientes dizem sobre nós e avalie nossos serviços no Google.' },
      zh: { title: '客户评价', description: '查看客户对我们的评价，并在 Google 上为我们的服务评分。' },
      he: { title: 'ביקורות לקוחות', description: 'ראה מה הלקוחות שלנו אומרים עלינו ודרג את השירותים שלנו בגוגל.' },
      ar: { title: 'آراء العملاء', description: 'شاهد ما يقوله عملاؤنا عنا وقيم خدماتنا على Google.' },
      ru: { title: 'ОТЗЫВЫ КЛИЕНТОВ', description: 'Посмотрите, что наши клиенты говорят о нас, и оцените наши услуги в Google.' },
      ro: { title: 'RECENZII CLIENȚI', description: 'Vedeți ce spun clienții noștri despre noi și evaluați serviciile noastre pe Google.' },
      nl: { title: 'KLANTBEOORDELINGEN', description: 'Bekijk wat onze klanten over ons zeggen en beoordeel onze diensten op Google.' },
      no: { title: 'KUNDEANMELDELSER', description: 'Se hva kundene våre sier om oss og vurder tjenestene våre på Google.' },
      hi: { title: 'ग्राहक समीक्षा', description: 'देखें कि हमारे ग्राहक हमारे बारे में क्या कहते हैं और Google पर हमारी सेवाओं को रेट करें।' },
      ja: { title: 'お客様の声', description: 'お客様の声をチェックして、Googleで当社のサービスを評価してください。' },
      fr: { title: 'AVIS CLIENTS', description: 'Découvrez ce que nos clients disent de nous et évaluez nos services sur Google.' },
      it: { title: 'RECENSIONI CLIENTI', description: 'Scopri cosa dicono di noi i nostri clienti e valuta i nostri servizi su Google.' },
      de: { title: 'KUNDENBEWERTUNGEN', description: 'Sehen Sie, was unsere Kunden über uns sagen, und bewerten Sie unsere Dienstleistungen auf Google.' },
      ko: { title: '고객 리뷰', description: '고객의 의견을 확인하고 Google에서 당사 서비스를 평가해 주세요.' },
      fi: { title: 'ASIAKASARVOSTELUT', description: 'Katso, mitä asiaksiimme sanovat meistä ja arvioi palvelumme Googlessa.' },
      el: { title: 'ΚΡΙΤΙΚΕΣ ΠΕΛΑΤΩΝ', description: 'Δείτε τι λένε οι πελάτες μας για εμάς και αξιολογήστε τις υπηρεσίες μας στο Google.' }
    }
  },
  {
    id: 'updates',
    icon: FileCheck,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    translations: {
      en: { title: 'APP UPDATES', description: 'Stay updated with the latest news, features, and improvements of our app.' },
      es: { title: 'ACTUALIZACIONES DE LA APP', description: 'Manténgase al día con las últimas noticias, funciones y mejoras de nuestra aplicación.' },
      pt: { title: 'ATUALIZAÇÕES DO APP', description: 'Fique atualizado com as últimas notícias, recursos e melhorias do nosso aplicativo.' },
      zh: { title: '应用更新', description: '随时了解我们应用的最新新闻、功能和改进。' },
      he: { title: 'עדכוני אפליקציה', description: 'הישאר מעודכן בחדשות, בתכונות ובשיפורים האחרונים של האפליקציה שלנו.' },
      ar: { title: 'تحديثات التطبيق', description: 'ابق على اطلاع بآخر الأخبار والميزات والتحسينات في تطبيقنا.' },
      ru: { title: 'ОБНОВЛЕНИЯ ПРИЛОЖЕНИЯ', description: 'Будьте в курсе последних новостей, функций и улучшений нашего приложения.' },
      ro: { title: 'ACTUALIZĂRI APLICAȚIE', description: 'Rămâneți la curent cu cele mai recente știri, funcții și îmbunătățiri ale aplicației noastre.' },
      nl: { title: 'APP-UPDATES', description: 'Blijf op de hoogte van het laatste nieuws, functies en verbeteringen van onze app.' },
      no: { title: 'APP-OPPDATERINGER', description: 'Hold deg oppdatert med de siste nyhene, funksjonene og forbedringene av appen vår.' },
      hi: { title: 'ऐप अपडेट', description: 'हमारे ऐप के नवीनतम समाचारों, सुविधाओं और सुधारों के साथ अपडेट रहें।' },
      ja: { title: 'アプリの更新', description: 'アプリの最新ニュース、機能、改善点について常に最新情報を入手してください。' },
      fr: { title: 'MISES À JOUR DE L\'APP', description: 'Restez informé des dernières nouvelles, fonctionnalités et améliorations de notre application.' },
      it: { title: 'AGGIORNAMENTI APP', description: 'Rimani aggiornato con le ultime notizie, funzionalità e miglioramenti della nostra app.' },
      de: { title: 'APP-UPDATES', description: 'Bleiben Sie auf dem Laufenden mit den neuesten Nachrichten, Funktionen und Verbesserungen unserer App.' },
      ko: { title: '앱 업데이트', description: '앱의 최신 뉴스, 기능 및 개선 사항을 최신 상태로 유지하세요.' },
      fi: { title: 'SOVELLUSPÄIVITYKSET', description: 'Pysy ajan tasalla sovelluksemme uusimmista uutisista, ominaisuuksista ja parannuksista.' },
      el: { title: 'ΕΝΗΜΕΡΩΣΕΙΣ ΕΦΑΡΜΟΓΗΣ', description: 'Μείνετε ενημερωμένοι με τα τελευταία νέα, λειτουργίες και βελτιώσεις της εφαρμογής μας.' }
    }
  },
  {
    id: 'partners',
    icon: Handshake,
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
    externalPlatformLink: 'https://flytour.com.br/',
    partners: [
      { name: 'FLYTOUR', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=400' },
      { name: 'ONER TRAVEL', image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80&w=400' },
      { name: 'RESERVIA', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=400' },
      { name: 'QUALITOURS', image: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&q=80&w=400' },
      { name: 'ETRADUÇÕES', image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400' },
      { name: 'YELLOWLING', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400' },
      { name: 'CHANTECLAIR', image: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&q=80&w=400' },
      { name: 'CADASTUR', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=400' }
    ],
    translations: {
      en: { title: 'PARTNERS', description: 'VGOIRE works with the most trusted companies in the travel and translation industry to ensure the best quality for our clients.' },
      es: { title: 'SOCIOS', description: 'VGOIRE trabaja con las empresas más confiables en la industria de viajes y traducción para garantizar la mejor calidad para nuestros clientes.' },
      pt: { title: 'PARCEIROS', description: 'A VGOIRE trabalha com as empresas mais confiáveis do setor de viagens e tradução para garantir a melhor qualidade aos nossos clientes.' },
      zh: { title: '合作伙伴', description: 'VGOIRE 与旅游和翻译行业最值得信赖的公司合作，确保为我们的客户提供最佳质量。' },
      he: { title: 'שותפים', description: 'VGOIRE עובדת עם החברות המהימנות ביותר בתעשיית הנסיעות והתרגום כדי להבטיח את האיכות הטובה ביותר עבור לקוחותינו.' },
      ar: { title: 'شركاؤنا', description: 'تعمل VGOIRE مع أكثر الشركات موثوقية في صناعة السفر والترجمة لضمان أفضل جودة لعملائنا.' },
      ru: { title: 'ПАРТНЕРЫ', description: 'VGOIRE работает с самыми надежными компаниями в сфере туризма и переводов, чтобы обеспечить лучшее качество для наших клиентов.' },
      ro: { title: 'PARTENERI', description: 'VGOIRE lucrează cu cele mai de încredere companii din industria călătoriilor și traducerilor pentru a asigura cea mai bună calitate clienților noștri.' },
      nl: { title: 'PARTNERS', description: 'VGOIRE werkt samen met de meest vertrouwde bedrijven in de reis- en vertaalindustrie om de beste kwaliteit voor onze klanten te garanderen.' },
      no: { title: 'PARTNERE', description: 'VGOIRE samarbeider med de mest pålitelige selskapene i reise- og oversettelsesbransjen for å sikre den beste kvaliteten for våre kunder.' },
      hi: { title: 'भागीदार', description: 'VGOIRE यात्रा और अनुवाद उद्योग की सबसे भरोसेमंद कंपनियों के साथ काम करता है ताकि हमारे ग्राहकों के लिए सर्वोत्तम गुणवत्ता सुनिश्चित की जा सके।' },
      ja: { title: 'パートナー', description: 'VGOIREは、旅行および翻訳行业で最も信頼されている企业と协力して、お客様に最高の品质を保证します。' },
      fr: { title: 'PARTENAIRES', description: 'VGOIRE travaille avec les entreprises les plus fiables du secteur du voyage et de la traduction pour garantir la meilleure qualité à nos clients.' },
      it: { title: 'PARTNER', description: 'VGOIRE collabora con le aziende più affidabili nel settore dei viaggi e delle traduzioni per garantire la migliore qualità ai nostri clienti.' },
      de: { title: 'PARTNER', description: 'VGOIRE arbeitet mit den vertrauenswürdigsten Unternehmen der Reise- und Übersetzungsbranche zusammen, um unseren Kunden die beste Qualität zu bieten.' },
      ko: { title: '파트너', description: 'VGOIRE는 여행 및 번역 업계에서 가장 신뢰받는 회사들과 협력하여 고객에게 최고의 품질을 보장합니다.' },
      fi: { title: 'KUMPPANIT', description: 'VGOIRE tekee yhteistyötä matkailu- ja käännösalan luotettavimpien yritysten kanssa varmistaakseen parhaan laadun asiakkaillemme.' },
      el: { title: 'ΣΥΝΕΡΓΑΤΕΣ', description: 'Η VGOIRE συνεργάζεται με τις πιο αξιόπιστες εταιρείες στον κλάδο των ταξιδιών και των μεταφράσεων για να εξασφαλίσει την καλύτερη ποιότητα για τους πελάτες μας.' }
    }
  },
];
